assign:
  name: Assign entity to device
  description: Assigns an existing entity to a specific device.
  fields:
    entity_id:
      required: true
      description: The ID of the entity that will be assigned to the device.
      example: "sensor.example_sensor"
      selector:
        entity:
          multiple: true
    device_id:
      required: true
      description: The ID of the device to which the entity will be assigned.
      example: "9ede4ee75fe68ef29a139980b1eb756d"
      selector:
        device:

unassign:
  name: Unassign entity from device
  description: Removes the assignment of an entity from its device.
  fields:
    entity_id:
      required: true
      description: The ID of the entity that will be unassigned from the device.
      example: "sensor.example_sensor"
      selector:
        entity:
          multiple: true
    device_id:
      required: true
      description: The ID of the device from which the entity will be unassigned.
      example: "9ede4ee75fe68ef29a139980b1eb756d"
      selector:
        device:

status:
  name: Get assignment status
  description: Returns the current assignment status of entities and devices.
